---

- name: Add the user 'codebeamer'
  ansible.builtin.user:
    name: codebeamer
    comment: codebeamer application account
    state: present

- include_tasks: codebeamer-install.yml
- include_tasks: selinux.yml
- include_tasks: firewall.yml
- include_tasks: certificate.yml
- include_tasks: systemd.yml



