---
- name: Add the user 'codebeamer'
  ansible.builtin.user:
    name: codebeamer
    comment: codebeamer application account
    state: present

- name: Copy CodeBeamer File to Codebeamer user folder  
  copy:
    src: 'files/{{ __codebeamer_installer }}'
    dest: '/home/codebeamer'
    owner: codebeamer
    group: root
    mode: 0550

- name: Check if installation exists
  become: yes
  become_user: codebeamer
  stat:
    path: '{{ __codebeamer_install_dir }}'
  register: codebeamer_install_status

- name: Extract Contents of binary file
  become: yes
  become_user: codebeamer
  ansible.builtin.expect:
    command: sh /home/codebeamer/{{ __codebeamer_installer }} --quiet --accept
    responses:
      '.*Directory.*:': '{{ __codebeamer_install_dir }}'
      '.*Do you want to read the CUSTOMER AGREEMENT.*': 'n'
      '.*Do you agree with the CUSTOMER AGREEMENT.*': 'y'
      '.*Please enter the TCP/IP portnumber for codebeamer.*': '8080'
      '.*Please enter the SSL TCP/IP portnumber for codebeamer.*': '8443'
      '.*Please enter the SHUTDOWN portnumber for codebeamer.*': '8005'
      '.*Do you want to download MySQL JDBC driver and accept its license.*': 'n'
      '.*Do you want to upgrade from your existing codebeamer installation.*': 'n'
      '.*Do you want to start codebeamer setup wizard now.*': 'n'
  when: not codebeamer_install_status.stat.exists

- name: Create a codebeamer symbolic link
  ansible.builtin.file:
    src: '{{ __codebeamer_install_dir }}'
    dest: '{{ __codebeamer_sym_link  }}'
    owner: codebeamer
    group: root
    state: link

- name: Copy CodeBeamer File to Codebeamer user folder
  copy:
    src: 'files/{{ __my_sql_connector_name }}'
    dest: "{{ ( __codebeamer_install_dir ,'tomcat/webapps/cb/WEB-INF/lib', __my_sql_connector_name) | path_join }}"
    owner: codebeamer
    group: root
    mode: 0550

- name: Update Permissions on the start files so that SELinux allows them to run correctly
  command: 
    cmd:  chcon -R -t bin_t {{ __codebeamer_sym_link }}/bin

- name: Copy codebeamer.service to /etc/systemd/system/
  template:
    src: "codebeamer.service.cnf.j2"
    dest: "/etc/systemd/system/codebeamer.service"
    owner: root
    group: root
    mode: 0444

- name: Enable Codebeamer service
  ansible.builtin.service:
    name: codebeamer
    state: started
    enabled: true