---
- name: Disable Online Repos
  block:
    - name: disable repos
      command: "subscription-manager repos --disable {{ item }}"
      with_items:
      - rhel-8-for-x86_64-appstream-rpms
      - rhel-8-for-x86_64-baseos-rpms

- name: Remove any DVD Mount first
  mount:
    path: /dvd    
    state: unmounted      

- name: Mount DVD read-only
  mount:
    path: /dvd
    src: /dev/cdrom
    fstype: auto
    opts: ro,noauto
    state: mounted      
  
- name: Update Repos
  copy:
    src: '{{ item }}'
    dest: '/etc/yum.repos.d/'
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - files/repos/*

- name: Remove Epel Repo files repos that was created from above
  shell: rm -rf /etc/yum.repos.d/*epel*

- name: Install epel-release (disble all repos bar epel for this install to prevent .repo files been created)
  yum:
    name: epel-release
    enablerepo: 'dvd-Epel'
    state: present

- name: Remove Epel Repo files repos that was created from above
  shell: rm -rf /etc/yum.repos.d/*epel*

- name: Install Open JDK packages
  yum:
    name: [java-17-openjdk.x86_64,glibc-langpack-en]
    exclude: '*-doc.noarch'
    state: present    

- name: Install Texlive packages
  yum:
    name: [texlive,texlive-latex,texlive-xetex,texlive-collection-latex,texlive-collection-latexrecommended]    
    state: present        
     
- name: Install ImageMagick packages
  yum:
    name: ImageMagick
    state: present        
    exclude: '*-doc.noarch' 
  
- name: Extract PhantomJS
  unarchive:
    src: 'files/phantomjs-2.1.1-linux-x86_64.tar.bz2'
    dest: '/opt'

- name: Create Symlink for PhantomJS
  ansible.builtin.file:
    src: '/opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs'
    dest: '/usr/local/bin/phantomjs'    
    state: link

- name: Install required python packages
  yum:
    name: [python3-PyMySQL,libselinux-python3,policycoreutils-python3]
    state: present   

- name: Install git packages
  yum:
    name: git239-2.39.0-0.2.el8.x86_64
    state: present     
    allowerasing: true    

- name: Install git-lfs packages
  yum:
    name: git-lfs-3.3.0-1.el8.x86_64
    state: present 

- name: Install SELinux utils
  yum:
    name: policycoreutils-devel
    state: present     
    
